### ISSUE TITLE
Check disabled dates whithin the range.

### ISSUE THREAD

**Issue by cjlaborde** [joffreyBerrier/vue-hotel-datepicker#14]
https://github.com/krystalcampioni/vue-hotel-datepicker/issues/188
Perhaps you could resolve this issue.

I did so by 
```js
            calculateReservedDates() {
                return this.disabledDates.map(disabledDate => moment(disabledDate).isBetween(this.start_date, this.end_date)).includes(true);
            },
```
Yet would be great if this was added as default.
Since this is a very crucial aspect of a reservation calendar it should not allow you to make reservations if your date range includes days from the disabled dates
```html
<HotelDatePicker
 :disabledDates="['2018-01-01', '2018-01-11', '2018-01-21' ]">
</HotelDatePicker>
```

**Comment by joffreyBerrier** [comment]
Hi @cjlaborde 

If you put on `disableDates` `['2018-01-01', '2018-01-30']` do you want to disable the entire month ?

I think it’s not the good way because it is a breaking changes

I think it's better to create an other array, like `rangeDisableDates`

In my case if I want to disable dates I would disable this specific date, not the range

**Comment by cjlaborde** [comment]
I going to check it later. Good to know.
YOu did great work with this component is a lot better than original.
